# Generated by Django 3.2 on 2024-02-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
        ('option', '0003_remove_option_is_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=256)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='option.option')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='avto.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.optionvalue')),
                ('post_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option.postoption')),
            ],
            options={
                'unique_together': {('post_option', 'option_value')},
            },
        ),
    ]
