# Generated by Django 3.2 on 2024-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_postoption_postoptionvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoption',
            name='value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
