# Generated by Django 5.0.2 on 2024-02-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentToOwn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_rent', models.BooleanField(default=False)),
                ('pre_payment', models.IntegerField()),
                ('rent_period', models.IntegerField()),
                ('payment_for_month', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_bargain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_salon',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('Andijan Region', 'Andijan Region'), ('Bukhara Region', 'Bukhara Region'), ('Fergana Region', 'Fergana Region'), ('Jizzakh Region', 'Jizzakh Region'), ('Karakalpakstan', 'Karakalpakstan (Autonomous Republic)'), ('Namangan Region', 'Namangan Region'), ('Navoiy Region', 'Navoiy Region'), ('Qashqadaryo Region', 'Qashqadaryo Region'), ('Samarkand Region', 'Samarkand Region'), ('Sirdaryo Region', 'Sirdaryo Region'), ('Surxondaryo Region', 'Surxondaryo Region'), ('Tashkent Region', 'Tashkent Region')], max_length=128)),
                ('phone_number', models.IntegerField()),
                ('is_agree', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaveAndNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('add_note', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveandnote', to='avto.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
